version: '3'
services:
  db:
    image: postgres
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: quiz_service_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8000:8000
    links:
      - dbmate
    depends_on:
      - db

  dbmate:
    image: amacneil/dbmate
    command: -d "/code/etc/db/migrations" up
    volumes:
      - .:/code
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/quiz_service_db?sslmode=disable