version: '3'
services:
  db:
    image: postgres
    env_file:
      - .env
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8000:8000
    links:
      - dbmate
    depends_on:
      - db

  dbmate:
    image: amacneil/dbmate
    command: -d "/code/etc/db/migrations" up
    env_file:
      - .env
    volumes:
      - .:/code
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://$DB_USER:$DB_PASSWORD@$DB_HOST/$DB_NAME?sslmode=disable

volumes:
  db-data: